### ISSUE TITLE
Send Chat Message to a Teams Channel

### ISSUE THREAD

**Issue by dpetrek** [Seidlm/Microsoft-Graph-API-Examples#1]
Hi,
the script provided does not work as expected.

PS C:\Users\dpetrek> $TeamID=((Invoke-RestMethod -Method GET -Uri $URLgetteamid  -Headers $headers).value | Where-Object -property displayName -value $TeamName -eq).id
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At line:1 char:11
+ $TeamID=((Invoke-RestMethod -Method GET -Uri $URLgetteamid  -Headers  ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Looks like API changed...

**Comment by Seidlm** [comment]
Hi, it seems more you do not have proper permissions to get the teamid
