### ISSUE TITLE
send email with high priority

### ISSUE THREAD

**Issue by oalimerko** [Seidlm/Microsoft-Graph-API-Examples#2]
what if i want to send an email with high priority ,what kind of headers should i use?
These headers did not help `X-Priority: 1` `X-MSMail-Priority: High`  `Importance: High`

**Comment by Seidlm** [comment]
hi, that should be a part of the Message Container, see: https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0

so

                        "message": {
                          "subject": "Hello World from Microsoft Graph API",
                          "importance": "high",
                          "body": {
                            "contentType": "HTML",
                            "content": "This Mail is sent via Microsoft <br>
                            GRAPH <br>
                            API<br>
                            
                            "
                          },
